server:
  port: 9006
 
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.8.82
      database: spitdb
  redis:
    host: 192.168.8.82
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true   
 