server:
  port: 9005
  
spring:
  application:
    name: tensquare-gathering
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.82:3306/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: zxguo
  jpa:
    database: mysql
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true    