server:
  port: 12000
  
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/sam_git/tensquare-config.git
          username: 
          password: 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true


    