server: 
  port: 9009
  
spring: 
  application:  
    name: tensquare-sms
  rabbitmq: 
    host: 192.168.43.101
aliyun: 
  sms:  
    accessKeyId:  LTAI8wOIWCNQAgQR
    accessKeySecret: 9KoqBP4HtxfxoqDgXsLzMZtw6HzyBq  
    template_code:  SMS_157683806
    sign_name:  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true