server:
  port: 9003
  
spring:
  application:
    name: tensquare-qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.82:3306?tensquare_qa?characterEncoding=UTF8
    username: root
    password: zxguo
  jpa:
    database: mysql
    show-sql: true